# Generated by Django 2.1.1 on 2018-09-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarningMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(max_length=300)),
                ('face', models.ImageField(upload_to='img')),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
